### ISSUE TITLE
Default page title title is *smaller* than h1 in body of page

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#112]
If you create a page in default okfn them the page title (set in wordpress title) is _smaller_ than h1 in body of page (and h2 too!)

This does not look right and suggest we make page title bigger (perhaps also true for posts ...)

Example: 

![hangouts the openspending blog](https://f.cloud.github.com/assets/180658/926252/3896c4e6-ff88-11e2-9dea-a79b2fb60aa4.png)

**Comment by smth** [comment]
I think this is due to the page title being an h2.

There is an SEO decision to be made here, i.e., should the h1 be a site-wide one, such as the strapline, or should it be the page title. Either way, we probably shouldn't be putting h1s into the page (a page should only have one h1 in my view).

In terms of visually defining the heading hierarchy, as it stands I think we do have the option to add headings at the same size as the page title (an h2), or smaller (h3, h4, h5, h6). This gives us a good array of options.

As I alluded to though, not having an h1, is not ideal for SEO, so we should sort that out.

**Comment by rufuspollock** [comment]
I'd suggest upping .page-title h2 or whatever it is at least for visual purposes (note h2 in page title is smaller than h2 in page - not just h1). Question of use of h1 in page (for SEO) or o/w is a different issue and hard to enforce so I'd suggest we just make the h2 of page title big enough to look appropriate :-)

**Comment by smth** [comment]
Ok, we should probably make the page titles h1s then..
