### ISSUE TITLE
OpenData page on okfn.org

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#17]
Proposed quite a while ago but still in progress. Really worth completing and launching IMO (RP).

**Comment by rufuspollock** [comment]
@ddie and @mintcanary had a chat yesterday but Daniel had not yet reviewed or prepared content.

**Comment by smth** [comment]
Talked more about this today. Daniel proposed a layout similar to okfn.org/services
We discussed having this video feature at the top of the page http://vimeo.com/21711338
@ddie will review and finalise the text today (possibly post link to it here for discussion?). After which I shall produce a mockup.

**Comment by rufuspollock** [comment]
I'm concerned that video is rather long. I also think we might want a quick set of carousel style slides on the main items at the very top.

As an alternative video (I know it is me talking!) I wonder about: http://blog.okfn.org/2012/04/02/talk-at-lift-2012-open-data-how-we-got-here-and-where-were-going/

**Comment by smth** [comment]
Draft text from @ddie http://opengovernmentdata.okfnpad.org/opendata

Comments from @rgrp 

Text 1.0 section at the bottom. This page is more about the place for
people to go to find out about open data rather than the palce to find
out what _we_ do about opendata.

Text 2.0 section: seems to cover both why and what. Perhaps focus on
What and then have a section on Why. (as per OGD.org)

Text 3.0: I would have this cover several topics. This isn't just
about OGD but about open science data, open geodata etc. I'd suggest a
topic like: What kinds of open data? And then have nice little square
block for each area with summary and links to further info and e.g.
our working groups in each area

General: every section should have further info links (this is a
chance to link to all the awesome stuff we do)

**Comment by smth** [comment]
Initial design, based on above: https://raw.github.com/okfn/okfn.org/master/designs/opendata_01.jpg

**Comment by noelmas** [comment]
Initial design looks excellent @ddie - I still feel the copy needs work. For instance, the section "What is Open Data?" seems to address the question of why rather what.

I would suggest we re-do section 1 addressing what is data and when is it open.

Then have a section on why open instead of the section on "What kinds of open data?" which I don't think is very helpful.

@ddie - would you like to re-draft or shall I have a go?

**Comment by smth** [comment]
Data types diagram: https://raw.github.com/okfn/okfn.org/master/designs/data-types-1.jpg

**Comment by noelmas** [comment]
This looks great. What's the plan to include providers of data and where do the annotations go with examples?

**Comment by rufuspollock** [comment]
Looks great. Only comment is that I think the What Kind of Open Data gets a bit lost vis a vis the image.

I really think we will be limited what can be in the diagram. Think we can probably do something fancy with image map or javascript.

We also definitely but our name in there as well on there (with simple (c) plus attribution license :-) )

**Comment by smth** [comment]
The plan is to use a tool tip like this http://i.imgur.com/MweA4.jpg
This would most likely be the Bootstrap tool tip, as it is already included in the theme.

I have made the heading bolder.

Our name in the diagram?

**Comment by smth** [comment]
This is the full page, as it stands https://raw.github.com/okfn/okfn.org/master/designs/opendata_02.jpg

**Comment by noelmas** [comment]
Open Data page is now live - it's a great start, and good to have it up. How does @rgrp add in information about example projects to diagram of types of open data? Is there a way?

**Comment by smth** [comment]
I can either add in the markup with space to add in the text, or, probably easiest, I can add it in once it has been written.

**Comment by noelmas** [comment]
@rgrp can you add for each box of table in https://docs.google.com/document/d/13vWd5ALf27WmneT6PrwTcaUfjhukYRgrzVZ8UjFHSIE/edit compelling open example

**Comment by noelmas** [comment]
@mintcanary please can we change climate > weather on "types of data"

**Comment by smth** [comment]
Done.
