### ISSUE TITLE
Consolidated and improved team page

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.org#65]
http://okfn.org/about/team/

Suggest:
- Consolidated core and projects team into the one main page
- Deprecate international chaper / local group teams for the present (bound to get out of date?)
- Ditto for working group teams page

Also tie this into usual induction workflow ...

**Comment by lauranewman** [comment]
- Agree about deprecating working group team page & chapter page (coordinators better listed elsewhere?)
- Rationale behind splitting project / core was that the old team page had become unwieldy and confusing. Distinction does often feel artificial, but would need some clear page-layout & organisation if we were to consolidate again.
- This _is_ part of induction workflow (http://wiki.okfn.org/Handbook/Induction#Core), but often gets pushed down the list (people don't have a photo ready or don't want to write bio on day one). I chase new starters periodically. The system could be better.

**Comment by keyboardkat** [comment]
@rgrp @lauranewman agreed re: depreciation of WG / chapter pages - are definitely going to get inaccurate due to high quantity of people playing 'coordinator' roles there (and it'd be good to keep our paid 'core' team separate from these folks, as many of them are unpaid volunteers).

**Comment by noelmas** [comment]
+1 to Rufus's suggestion. We can see that the Projects Page is already quite out of date with Jilly and Tom still there. I would suggest that we list people specifically focussed on project and not part of core elsewhere (on a project website as we do for the WGs). Otherwise this will constantly be going out of date.

**Comment by rufuspollock** [comment]
To be clear I was suggesting consolidating projects and core into one page - I don't think there is really a useful distinction here. so there would still be a need to keep up to date (but that's part of a process we should be doing anyway).

**Comment by LaurieJ** [comment]
The problem which was addressed _last time_ was that you couldn't tell what anyone did.  We were just a mass of people.  THe projects/core distinction no longer makes sense, but then we expect to bring in a new structure which will make much more sense, with new role titles, in the coming weeks. I'd suggest we minimise effort on rework now and assume we'll need a big rework shortly. 

Our people turnover quickly and the out of dateness is just because of that. Again, we need stronger joiner/leaver processes and Michelle is working on those :)

**Comment by rufuspollock** [comment]
@mintcanary can we at least deprecate (i.e. delete - i'd suggest copying current content into an html comment in main team page so we have a backup):
- international chapter
- working groups team pages for the present.
- merge the core team and projects team into the main page
- remove the big photo at the top

For the rest, I guess key first steps would be what are we going to show? My guess is name, role and headshot plus link to their profile page (?).

**Comment by smth** [comment]
Done. I haven't touched the sub pages, just removed links to them.

**Comment by rufuspollock** [comment]
FIXED. Much improved a couple of months ago!
