### ISSUE TITLE
Change four blog posts to three on front page

### ISSUE THREAD

**Issue by noelmas** [okfn/okfn.org#67]
Feedback has pointed out that it is misleading that the four boxes about what we promote line up so neatly with the blog posts as if they are part of the same column / theme.

Suggest reverting back to only having three blog posts there so they no longer line up

**Comment by smth** [comment]
I have to say, I think the problem is with the four headings, not the number of blog posts. Reducing the number of post will break this connection, but people will still be confused about what those headings are about, they may even start to associate them with the text above. I'd rather we address the problem directly (somehow), rather than try to minimise the damage..

**Comment by noelmas** [comment]
Hmmm... I like the four headings and feel that they give people a sense of what we're about. I really don't want to take them out.
Can you think of a way of styling them that would make them more stand alone and look unclickable...

**Comment by smth** [comment]
How about we move them into the first slide? This also has the advantage of having a clear statement near the top of the page. https://raw.github.com/okfn/okfn.org/master/designs/okfn_08_home_09.jpg

**Comment by noelmas** [comment]
This is great. Please implement. Do you feel that the only thing now is that the left side is a bit text heavy? Any recommendations for breaking up the text a bit, maybe we could embed a picture underneath Intro the OKFN rather than having that first para...

**Comment by smth** [comment]
Yeah, that's not a bad idea, I'll see what I can do..

**Comment by smth** [comment]
Implemented.
