### ISSUE TITLE
Newsletter Signup

### ISSUE THREAD

**Issue by smth** [okfn/okfn.org#84]
I see the Mailchimp signup bar has been removed from okfn.org, is this intentional?

**Comment by rufuspollock** [comment]
No i moved it to the footer ... (or at least attempted to - thought i set right values int he config but i may have got confused since can't see it there now ...)

Personally I think we probably want it in the body below the fold rather than in the footer or at the very top of the page (which is a bit weird ...)

**Comment by smth** [comment]
I have reactivated it now.
The last brief requested it to be in the same position as on sunlightfoundation.com, which is just above the footer, which is where it is..

**Comment by rufuspollock** [comment]
@mintcanary much appreciated!
